export enum ActionType {
  SIGN_MESSAGE = 'SIGN_MESSAGE',
  SEND_TRANSACTION = 'SEND_TRANSACTION',
  SIGN_TRANSACTION = 'SIGN_TRANSACTION',
  CONFIRM_TRANSACTION = 'CONFIRM_TRANSACTION',
}

export enum ActionStatus {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
}
