export const MALFORMED_PHONE_NUMBER = 'MALFORMED_PHONE_NUMBER';
export const INCORRECT_VERIFICATION_CODE = 'INCORRECT_VERIFICATION_CODE';
export const VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED';
export const MAX_TRIES_EXCEEDED = 'MAX_TRIES_EXCEEDED';
export const AUTH_METHOD_FORBIDDEN = 'AUTH_METHOD_FORBIDDEN';
export const ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS';
