{{- if .Values.ingress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginxinc-pub
    nginx.org/max-fails: "0"
  labels:
    {{- include "magic-app.podLabels" . | nindent 4 }}
    {{- include "magic-app.selectorLabels" . | nindent 4 }}
  name: {{ include "magic-app.name" . }}
  namespace: {{ .Values.previewNamespace | default .Values.deployEnv }}
spec:
  rules:
  - host: auth-{{ .Values.previewNamespace | default .Values.deployEnv }}.stagef.magic.link
    http:
      paths:
      - backend:
          service:
            name: {{ include "magic-app.name" . }}
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
{{- end }}
