{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magic-app.name" . }}
  namespace: {{ .Values.previewNamespace | default .Values.deployEnv }}
  labels:
    {{- include "magic-app.podLabels" . | nindent 4 }}
    {{- include "magic-app.selectorLabels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.deployment.appContainer.port }}
      protocol: TCP
      targetPort: {{ .Values.deployment.appContainer.port }}
  selector:
    app: {{ include "magic-app.name" . }}
    deploy_env: {{ .Values.deployEnv }}
{{- end }}
