{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "eks-{{ include "magic-app.name" . }}"
  namespace: {{ .Values.previewNamespace | default .Values.deployEnv }}
  labels:
    {{- include "magic-app.podLabels" . | nindent 4 }}
    {{- include "magic-app.selectorLabels" . | nindent 4 }}
{{- end }}
