// NOTE - if you add a code here, you must also add it to the datadog-error-classification.ts map as an 'error', 'warn', or 'info' type
export enum ControlFlowErrorCode {
  UnknownError,
  LoginWithMagicLinkFailedVerification,
  LoginWithMagicLinkExpired,
  LoginRedirectLoginComplete,
  LoginWithMagicLinkRateLimited,
  MalformedEmail,
  InvalidAPIKey,
  GenericServerError,
  RequestNotAuthorizedForDomain,
  RequestNotAuthorizedForDomainInRelayer,
  RequestNotAuthorizedForBundle,
  AllowlistConfigurationRequired,
  RateLimitExceeded,
  APIKeyMissing,
  SecretAPIKeyShouldNotBeProvided,
  EnhancedEmailValidation,
  ForbiddenForFreeDeveloperPlan,
  EmailUpdateConfirmLinkExpired,
  EmailUpdateFailedConfirmation,
  DuplicateEmail,
  InvalidEmailUpdateToken,
  OverMAUQuota,
  AnomalousRequestDetected,
  AnomalousRequestApprovalRequired,
  EmailUpdateEmailSent,
  InvalidRedirectURL,
  InvalidTestModeEmail,
  InactiveRecipient,
  APIAccessSuspended,
  UnsupportedEthereumNetwork,
  UserEmailNotAllowed,
  UserEmailBlocked,
  DisabledAuthMethod,
  MAUServiceLimitExceeded,
  InvalidApiKeyType,
  MagicLinkRequestedFromDifferentIp,
  UserDeviceNotVerified,
  DeviceVerificationLinkExpired,
  DeviceNotSupported,
}

// NOTE - if you add a code here, you must also add it to the datadog-error-classification.ts map as an 'error', 'warn', or 'info' type
export enum ContolFlowMappedErrorCode {
  AUTH_PASSWORDLESS_LOGIN_EMAIL_SENT = 'AUTH_PASSWORDLESS_LOGIN_EMAIL_SENT',
  INVALID_API_KEY = 'INVALID_API_KEY',
  REQUEST_NOT_AUTHORIZED_FOR_DOMAIN = 'REQUEST_NOT_AUTHORIZED_FOR_DOMAIN',
  REQUEST_NOT_AUTHORIZED_FOR_BUNDLE = 'REQUEST_NOT_AUTHORIZED_FOR_BUNDLE',
  ALLOWLIST_CONFIGURATION_REQUIRED = 'ALLOWLIST_CONFIGURATION_REQUIRED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  API_KEY_IS_MISSING = 'API_KEY_IS_MISSING',
  SECRET_API_KEY_SHOULD_NOT_BE_PROVIDED = 'SECRET_API_KEY_SHOULD_NOT_BE_PROVIDED',
  FORBIDDEN_FOR_FREE_DEVELOPER_PLAN = 'FORBIDDEN_FOR_FREE_DEVELOPER_PLAN',
  EXPIRED_EMAIL_UPDATE = 'EXPIRED_EMAIL_UPDATE',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  INVALID_AUTH_PASSWORDLESS_LOGIN_REQUEST = 'INVALID_AUTH_PASSWORDLESS_LOGIN_REQUEST',
  REDIRECT_CONTEXT_LOGIN_COMPLETED = 'REDIRECT_CONTEXT_LOGIN_COMPLETED',
  MALFORMED_EMAIL = 'MALFORMED_EMAIL',
  ENHANCED_EMAIL_VALIDATION = 'ENHANCED_EMAIL_VALIDATION',
  INVALID_EMAIL_UPDATE_TOKEN = 'INVALID_EMAIL_UPDATE_TOKEN',
  OVER_MAU_QUOTA = 'OVER_MAU_QUOTA',
  ANOMALOUS_REQUEST_DETECTED = 'ANOMALOUS_REQUEST_DETECTED',
  ANOMALOUS_REQUEST_APPROVAL_REQUIRED = 'ANOMALOUS_REQUEST_APPROVAL_REQUIRED',
  MAGIC_LINK_REQUESTED_FROM_DIFFERENT_IP = 'MAGIC_LINK_REQUESTED_FROM_DIFFERENT_IP',
  EMAIL_UPDATE_EMAIL_SENT = 'EMAIL_UPDATE_EMAIL_SENT',
  INVALID_REDIRECT_URL = 'INVALID_REDIRECT_URL',
  APP_DOMAIN_AND_REDIRECT_URL_DOMAIN_MISMATCH = 'APP_DOMAIN_AND_REDIRECT_URL_DOMAIN_MISMATCH',
  INVALID_TEST_MODE_EMAIL = 'INVALID_TEST_MODE_EMAIL',
  INACTIVE_RECIPIENT = 'INACTIVE_RECIPIENT',
  API_ACCESS_SUSPENDED = 'API_ACCESS_SUSPENDED',
  AUTH_METHOD_FORBIDDEN = 'AUTH_METHOD_FORBIDDEN',
  UNSUPPORTED_ETHEREUM_NETWORK = 'UNSUPPORTED_ETHEREUM_NETWORK',
  EMAIL_NOT_ALLOWED = 'EMAIL_NOT_ALLOWED',
  EMAIL_BLOCKED = 'EMAIL_BLOCKED',
  DEVICE_NOT_VERIFIED = 'DEVICE_NOT_VERIFIED',
  MAU_SERVICE_LIMIT_EXCEEDED = 'MAU_SERVICE_LIMIT_EXCEEDED',
  INVALID_API_KEY_TYPE = 'INVALID_API_KEY_TYPE',
  DEVICE_NOT_SUPPORTED = 'DEVICE_NOT_SUPPORTED',
  REQUEST_NOT_AUTHORIZED_FOR_DOMAIN_IN_RELAYER = 'REQUEST_NOT_AUTHORIZED_FOR_DOMAIN_IN_RELAYER',
}

export const endUserControlFlowErrors = [
  ControlFlowErrorCode.MalformedEmail,
  ControlFlowErrorCode.EnhancedEmailValidation,
  ControlFlowErrorCode.InactiveRecipient,
  ControlFlowErrorCode.DuplicateEmail,
  ControlFlowErrorCode.AnomalousRequestDetected,
  ControlFlowErrorCode.AnomalousRequestApprovalRequired,
  ControlFlowErrorCode.EmailUpdateEmailSent,
  ControlFlowErrorCode.DeviceNotSupported,
];

export const developerControlFlowErrors = [
  ControlFlowErrorCode.InvalidAPIKey,
  ControlFlowErrorCode.RateLimitExceeded,
  ControlFlowErrorCode.APIKeyMissing,
  ControlFlowErrorCode.SecretAPIKeyShouldNotBeProvided,
  ControlFlowErrorCode.OverMAUQuota,
  ControlFlowErrorCode.InvalidRedirectURL,
  ControlFlowErrorCode.APIAccessSuspended,
  ControlFlowErrorCode.UnsupportedEthereumNetwork,
  ControlFlowErrorCode.DisabledAuthMethod,
  ControlFlowErrorCode.InvalidApiKeyType,
];

export const requestNotAuthorizedErrors = [
  ControlFlowErrorCode.RequestNotAuthorizedForDomain,
  ControlFlowErrorCode.RequestNotAuthorizedForBundle,
  ControlFlowErrorCode.AllowlistConfigurationRequired,
];

export const userAccessControlFlowErrors = [
  ControlFlowErrorCode.UserEmailNotAllowed,
  ControlFlowErrorCode.UserEmailBlocked,
  ControlFlowErrorCode.MAUServiceLimitExceeded,
];

export const internalControlFlowErrors = [ControlFlowErrorCode.GenericServerError];
