export const LOGIN_THROTTLED = 'LOGIN_THROTTLED';
export const INCORRECT_VERIFICATION_CODE = 'INCORRECT_VERIFICATION_CODE';
export const VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED';
export const MAX_ATTEMPTS_EXCEEDED = 'MAX_ATTEMPTS_EXCEEDED';
