export const MALFORMED_PHONE_NUMBER = 'MALFORMED_PHONE_NUMBER';
export const LOGIN_THROTTLED = 'LOGIN_THROTTLED';
export const INCORRECT_VERIFICATION_CODE = 'INCORRECT_VERIFICATION_CODE';
export const VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED';

// Recovery factor
export const INVALID_FACTOR_VERIFIER_CREDENTIALS = 'INVALID_FACTOR_VERIFIER_CREDENTIALS';
