export const SET_TEST_MODE_USER_EMAIL = 'testMode/SET_TEST_MODE_USER_EMAIL';
export const SET_TEST_MODE_USER_KEYS = 'testMode/SET_TEST_MODE_USER_KEYS';
export const SET_TEST_MODE_USER_LOGIN_STATUS = 'testMode/SET_TEST_MODE_USER_LOGIN_STATUS';
export const TEST_MODE_LOGOUT = 'testMode/TEST_MODE_LOGOUT';
