export const SET_THIRD_PARTY_WALLET = 'connect/SET_THIRD_PARTY_WALLET';
export const SET_THIRD_PARTY_WALLET_LOGIN_FLOW_RESPONSE_DATA =
  'connect/SET_THIRD_PARTY_WALLET_LOGIN_FLOW_RESPONSE_DATA';
export const SET_THIRD_PARTY_WALLET_REQUEST_USER_INFO = 'connect/SET_THIRD_PARTY_WALLET_REQUEST_USER_INFO';
export const SET_LAST_SELECTED_LOGIN = 'connect/SET_LAST_SELECTED_LOGIN';
export const SET_WALLET_CONNECTIONS_INFO = 'connect/SET_WALLET_CONNECTIONS_INFO';
export const SET_ENABLED_THIRD_PARTY_WALLETS = 'SET_ENABLED_THIRD_PARTY_WALLETS';
export const SET_SELECTED_THIRD_PARTY_WALLET = 'SET_SELECTED_THIRD_PARTY_WALLET';
export const SET_THIRD_PARTY_WALLET_ENV = 'SET_THIRD_PARTY_WALLET_ENV';
