export const SET_OTP_EMAIL = 'auth/SET_OTP_EMAIL';
export const SET_EMAIL_OTP_SHOW_UI = 'auth/SET_EMAIL_OTP_SHOW_UI';
export const SET_EMAIL_OTP_SHOW_DEVICE_CHECK_UI = 'auth/SET_EMAIL_OTP_SHOW_DEVICE_CHECK_UI';
export const SET_EMAIL_OTP_WHITELABEL_ROM = 'auth/SET_EMAIL_OTP_WHITELABEL_ROM';
export const SET_LOGIN_WITH_EMAIL_OTP_PAYLOAD = 'auth/SET_LOGIN_WITH_EMAIL_OTP_PAYLOAD';
