export const SET_EMAIL_FORM = 'pnp/SET_EMAIL_FORM';
export const SET_PHONE_NUMBER_FORM = 'pnp/SET_PHONE_NUMBER_FORM';
export const SET_SELECTED_COUNTRY_CODE = 'pnp/SET_SELECTED_COUNTRY_CODE';
export const SET_PHONE_NUMBER_FOR_LOGIN = 'pnp/SET_PHONE_NUMBER_FOR_LOGIN';
