import { Network } from 'alchemy-sdk';
import { NETWORK_NAMES } from './network-names';

export const ALCHEMY_NETWORKS = {
  [NETWORK_NAMES.ETHEREUM]: Network.ETH_MAINNET,
  [NETWORK_NAMES.GOERLI]: Network.ETH_GOERLI,
  [NETWORK_NAMES.SEPOLIA]: Network.ETH_SEPOLIA,
  [NETWORK_NAMES.POLYGON]: Network.MATIC_MAINNET,
  [NETWORK_NAMES.POLYGON_MUMBAI]: Network.MATIC_MUMBAI,
  [NETWORK_NAMES.POLYGON_AMOY]: Network.MATIC_AMOY,
  [NETWORK_NAMES.OPTIMISM]: Network.OPT_MAINNET,
  [NETWORK_NAMES.OPTIMISM_GOERLI]: Network.OPT_GOERLI,
  [NETWORK_NAMES.ARBITRUM_ONE]: Network.ARB_MAINNET,
  [NETWORK_NAMES.ARBITRUM_SEPOLIA]: Network.ARB_SEPOLIA,
  [NETWORK_NAMES.BASE]: Network.BASE_MAINNET,
  [NETWORK_NAMES.BASE_SEPOLIA]: Network.BASE_SEPOLIA,
} as const;
