export const THEME_BRANDING_DEFAULT_VALUE = 1;
export const THEME_BRANDING_HIDE_MAGIC_LOGO_VALUE = 2;

export const THEME_BRANDING_DEFAULT = 'DEFAULT';
export const THEME_BRANDING_HIDE_MAGIC_LOGO = 'HIDE_MAGIC_LOGO';

export const CUSTOM_BRANDING_TYPE_VALUES = {
  [THEME_BRANDING_DEFAULT_VALUE]: THEME_BRANDING_DEFAULT,
  [THEME_BRANDING_HIDE_MAGIC_LOGO_VALUE]: THEME_BRANDING_HIDE_MAGIC_LOGO,
};
