export const SET_UI_THREAD_PAYLOAD = 'uiThread/SET_UI_THREAD_PAYLOAD';
export const SET_UI_THREAD_ERROR = 'uiThread/SET_UI_THREAD_ERROR';
export const SET_UI_THREAD_RENDER_FN = 'uiThread/SET_UI_THREAD_RENDER_FN';
export const SET_RETURN_ROUTE_PAGE_ID = 'uiThread/SET_RETURN_ROUTE_PAGE_ID';
export const SET_UI_THREAD_RESPONSE = 'uiThread/SET_UI_THREAD_RESPONSE';
