export const INCORRECT_VERIFICATION_CODE = 'INCORRECT_VERIFICATION_CODE';
export const VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED';
export const LOGIN_THROTTLED = 'LOGIN_THROTTLED';
export const MALFORMED_EMAIL = 'MALFORMED_EMAIL';
export const ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS';
