export const RECOVERY_FACTOR_ALREADY_EXISTS = 'RECOVERY_FACTOR_ALREADY_EXISTS';
export const MALFORMED_PHONE_NUMBER = 'MALFORMED_PHONE_NUMBER';
export const ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS';
export const INVALID_FACTOR_VERIFIER_CREDENTIALS = 'INVALID_FACTOR_VERIFIER_CREDENTIALS';
