export const INIT_RECENCY_CHECK = 'recency/INIT_RECENCY_CHECK';
export const SET_DESTINATION_AFTER_VERIFIED = 'recency/SET_DESTINATION_AFTER_VERIFIED';
export const SET_NEED_PRIMARY_FACTOR_VERIFICATION = 'recency/SET_NEED_PRIMARY_FACTOR_VERIFICATION';

export const SET_PRIMARY_FACTOR_CREDENTIAL = 'recency/SET_PRIMARY_FACTOR_CREDENTIAL';
export const SET_ATTEMPT_ID = 'recency/SET_ATTEMPT_ID';
