name: Tests
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - 'master'
  pull_request:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-base:
    name: Build builder-base image
    uses: ./.github/workflows/w_builder_base.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      ENCRYPTED_COOKIE_KEY: ${{ secrets.ENCRYPTED_COOKIE_KEY }}
      SIGNED_COOKIE_KEY: ${{ secrets.SIGNED_COOKIE_KEY }}
      DEPLOY_ENV: ${{ secrets.DEPLOY_ENV }}

  test:
    runs-on: ubuntu-20.04
    name: Run style/security checks & tests
    container:
      image: node:18.20.0-slim
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.0
          cache: 'npm'
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends python3 make g++ pkg-config libusb-1.0 libudev-dev
      - run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Audit Prod Dependencies
        run: yarn audit --groups dependencies || exit 0
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn test:unit && yarn test:e2e
